### ISSUE TITLE
Incompatible with Latest Autoprop Version

### ISSUE THREAD

**Issue by marky1991b** [kalekundert/autoprop#6]
Given this test script:

```
import glooey

class TilePickerButton(glooey.Widget):
    custom_alignment = 'center'
    custom_propagate_mouse_events = True

    def __init__(self, cls, on_mouse_press):
        super().__init__()
        self.cls = cls

        vbox = glooey.VBox()
        self.image = glooey.Image(cls.image)
        self.label = glooey.Label(cls.__name__)

        vbox.pack(self.image)
        vbox.add(self.label)
        import pdb
        #pdb.set_trace()
        vbox.padding = 6

        self._attach_child(vbox)
        self.on_mouse_press_func = on_mouse_press

    def on_mouse_press(self, x, y, button, modifiers):
        super().on_mouse_press(x, y, button, modifiers)
        print("pressed")
        return self.on_mouse_press_func()

class FakeSprite:
    image = "fake.png"

cls = FakeSprite
button = TilePickerButton(cls, lambda cls=cls: setattr(self, "active_content_cls", cls))
```

This code works using autoprop 0.0.3, but fails with the latest version, 3.0.0. The error:
```Traceback (most recent call last):
  File "test_glooey.py", line 33, in <module>
    button = TilePickerButton(cls, lambda cls=cls: setattr(self, "active_content_cls", cls))
  File "test_glooey.py", line 19, in __init__
    vbox.padding = 6
AttributeError: can't set attribute
```

This is happening because autoprop (at least as of 3.0.0) specifically validates that the setter accepts exactly one argument other than self and must be passed positionally. In older versions, it wasn't so strict (or at least, this example works when i run it using autoprop version 0.0.3) , but I checked and the documentation has always at least claimed this to be a requirement.

**Comment by marky1991b** [comment]
I'm sorry, I reported this against the wrong project altogether, please ignore.
